import type { ProviderMeta } from './types';

export const PROVIDERS: ProviderMeta[] = [
  {
    id: 'openclaw',
    name: 'OpenClaw',
    short: 'OpenClaw',
    symbol: '⚡',
    recommended: true,
    freeTier: true,
    description: 'OpenAI 兼容路由 · 免费额度可用',
    keyLabel: 'OpenClaw Access Token',
    keyPlaceholder: 'oc-•••••••••••••••',
    helperUrl: 'https://openclaw.dev',
    helperLabel: '获取免费 OpenClaw Token',
    models: [
      {
        id: 'openclaw-default',
        label: 'openclaw-default',
        context: 'auto',
        tags: ['Managed routing'],
        recommended: true,
      },
    ],
  },
  {
    id: 'anthropic',
    name: 'Anthropic Claude',
    short: 'Anthropic',
    symbol: '◆',
    description: 'Claude Opus 4.7 · 200K 上下文，原生多模态 (2026.04最新)',
    keyLabel: 'Anthropic API Key',
    keyPlaceholder: 'sk-ant-••••••••',
    helperUrl: 'https://console.anthropic.com',
    helperLabel: '前往 console.anthropic.com 获取密钥',
    warning: '推荐使用 Claude Opus 4.6/4.7 (2026年最新旗舰)',
    models: [
      {
        id: 'claude-opus-4-7',
        label: 'claude-opus-4-7 🆕',
        context: '200K ctx',
        tags: ['Smartest', 'Flagship 2026', 'Multi-modal'],
        recommended: true,
      },
      {
        id: 'claude-opus-4-6',
        label: 'claude-opus-4-6',
        context: '200K ctx',
        tags: ['Advanced', 'Adaptive thinking'],
      },
      {
        id: 'claude-sonnet-4-5',
        label: 'claude-sonnet-4-5',
        context: '200K ctx',
        tags: ['Balanced', 'Fast', '⭐ Best value'],
      },
      {
        id: 'claude-haiku-4-5',
        label: 'claude-haiku-4-5',
        context: '200K ctx',
        tags: ['Fastest', 'Cheapest'],
      },
    ],
  },
  {
    id: 'openai',
    name: 'OpenAI',
    short: 'OpenAI',
    symbol: '◉',
    description: 'GPT-5.5 系列 · 1M 上下文窗口 (2026.04最新)',
    keyLabel: 'OpenAI API Key',
    keyPlaceholder: 'sk-••••••••',
    helperUrl: 'https://platform.openai.com',
    helperLabel: '前往 platform.openai.com 获取密钥',
    warning: 'GPT-5.5 是2026年最新旗舰，支持1M上下文和视觉输入',
    models: [
      {
        id: 'gpt-5.5',
        label: 'gpt-5.5 🆕 Flagship',
        context: '1M ctx',
        tags: ['Smartest', 'Reasoning', 'Vision', 'Agentic coding'],
        recommended: true,
      },
      {
        id: 'gpt-5.5-pro',
        label: 'gpt-5.5-pro 🆕 Pro',
        context: '1M ctx',
        tags: ['Pro tier', 'Enhanced reasoning'],
      },
      {
        id: 'gpt-5.4-mini',
        label: 'gpt-5.4-mini 🆕 Fast',
        context: '1M ctx',
        tags: ['Fast', 'Cheap', 'Low latency'],
      },
      {
        id: 'gpt-4o',
        label: 'gpt-4o (Legacy)',
        context: '128K ctx',
        tags: ['Stable', 'Deprecated soon?'],
      },
    ],
  },
  {
    id: 'google',
    name: 'Google Gemini',
    short: 'Gemini',
    symbol: '✦',
    description: 'Gemini 2.5 / 3.x 系列 · 1M+ 上下文 (2026最新)',
    keyLabel: 'Google AI API Key',
    keyPlaceholder: 'AIza••••••••',
    helperUrl: 'https://aistudio.google.com',
    helperLabel: '前往 aistudio.google.com 获取密钥',
    warning: '⚠️ gemini-2.0-flash 将于2026/06/01废弃，请迁移到2.5-flash',
    models: [
      {
        id: 'gemini-2.5-pro',
        label: 'gemini-2.5-pro',
        context: '1M ctx',
        tags: ['Smartest', 'Free tier available'],
        recommended: true,
      },
      {
        id: 'gemini-2.5-flash',
        label: 'gemini-2.5-flash',
        context: '1M ctx',
        tags: ['Fast', 'Cost-effective'],
      },
      {
        id: 'gemini-2.0-flash',
        label: 'gemini-2.0-flash ⚠️ Deprecated 06/01',
        context: '1M ctx',
        tags: ['Deprecated', 'Migrate to 2.5-flash'],
      },
    ],
  },
  {
    id: 'deepseek',
    name: 'DeepSeek',
    short: 'DeepSeek',
    symbol: '▲',
    description: 'DeepSeek V4 系列 · 最新推理模型 (2026)',
    keyLabel: 'DeepSeek API Key',
    keyPlaceholder: 'sk-••••••••',
    helperUrl: 'https://platform.deepseek.com',
    helperLabel: '前往 platform.deepseek.com 获取密钥',
    warning: '🚨 deepseek-chat/reasoner 将于2026/07/24废弃！请使用V4版本',
    models: [
      {
        id: 'deepseek-v4-pro',
        label: 'deepseek-v4-pro 🆕',
        context: '128K ctx',
        tags: ['Latest', 'Strongest', 'Reasoning mode'],
        recommended: true,
      },
      {
        id: 'deepseek-v4-flash',
        label: 'deepseek-v4-flash 🆕 Fast',
        context: '128K ctx',
        tags: ['Fast', 'Lightweight'],
      },
      {
        id: 'deepseek-chat',
        label: 'deepseek-chat ⚠️ Deprecated 07/24',
        context: '64K ctx',
        tags: ['Deprecated', 'Use v4-flash instead'],
      },
      {
        id: 'deepseek-reasoner',
        label: 'deepseek-reasoner ⚠️ Deprecated 07/24',
        context: '64K ctx',
        tags: ['Deprecated', 'Use v4-pro instead'],
      },
    ],
  },
  {
    id: 'groq',
    name: 'GroqCloud',
    short: 'Groq',
    symbol: '○',
    description: '超高速推理 · Llama 4 / GPT OSS (2026最新)',
    keyLabel: 'Groq API Key',
    keyPlaceholder: 'gsk_••••••••',
    helperUrl: 'https://console.groq.com',
    helperLabel: '前往 console.groq.com 获取密钥',
    models: [
      {
        id: 'llama-3.3-70b-versatile',
        label: 'llama-3.3-70b-versatile',
        context: '128K ctx',
        tags: ['Best quality on Groq', '280 T/s'],
        recommended: true,
      },
      {
        id: 'meta-llama/llama-4-scout-17b-16e-instruct',
        label: 'Llama 4 Scout 17B 🆕',
        context: '131K ctx',
        tags: ['Newest', '750 T/s', 'Efficient'],
      },
      {
        id: 'openai/gpt-oss-120b',
        label: 'GPT OSS 120B 🆕',
        context: '131K ctx',
        tags: ['Open source GPT', '500 T/s'],
      },
      {
        id: 'openai/gpt-oss-20b',
        label: 'GPT OSS 20B 🆕',
        context: '131K ctx',
        tags: ['Open source GPT', '1000 T/s', 'Fastest'],
      },
      {
        id: 'llama-3.1-8b-instant',
        label: 'Llama 3.1 8B Instant',
        context: '131K ctx',
        tags: ['Ultra fast', '560 T/s', 'Lightweight'],
      },
      {
        id: 'groq/compound',
        label: 'Compound System 🆕',
        context: '131K ctx',
        tags: ['Multi-model system', '450 T/s'],
      },
    ],
  },
  {
    id: 'azure',
    name: 'Azure OpenAI',
    short: 'Azure',
    symbol: '⊞',
    description: 'Azure 托管的 OpenAI 部署 (支持GPT-5.x)',
    keyLabel: 'Azure API Key',
    keyPlaceholder: '•••••',
    models: [
      {
        id: 'azure-deployment',
        label: 'Your deployment',
        context: '—',
        tags: ['Custom'],
        recommended: true,
      },
    ],
  },
  {
    id: 'custom',
    name: 'Custom / OpenAI-compatible',
    short: 'Custom',
    symbol: '···',
    description: '自定义 OpenAI 兼容端点 (支持任何2026新模型)',
    keyLabel: 'API Key',
    keyPlaceholder: '•••••',
    models: [
      {
        id: 'custom-model',
        label: 'Your model',
        context: '—',
        tags: ['Custom'],
        recommended: true,
      },
    ],
  },
];

export function getProvider(id: string | null | undefined) {
  return PROVIDERS.find((p) => p.id === id) ?? null;
}
