import type { ProviderMeta } from "./types"

export const PROVIDERS: ProviderMeta[] = [
  {
    id: "openclaw",
    name: "OpenClaw",
    short: "OpenClaw",
    symbol: "⚡",
    recommended: true,
    freeTier: true,
    description: "OpenAI 兼容路由 · 免费额度可用",
    keyLabel: "OpenClaw Access Token",
    keyPlaceholder: "oc-••••••••••••••••",
    helperUrl: "https://openclaw.dev",
    helperLabel: "获取免费 OpenClaw Token",
    models: [
      {
        id: "openclaw-default",
        label: "openclaw-default",
        context: "auto",
        tags: ["Managed routing"],
        recommended: true,
      },
    ],
  },
  {
    id: "anthropic",
    name: "Anthropic Claude",
    short: "Anthropic",
    symbol: "◆",
    description: "Claude 系列 · 200K 上下文，最适合 SKILL.md",
    keyLabel: "Anthropic API Key",
    keyPlaceholder: "sk-ant-••••••••",
    helperUrl: "https://console.anthropic.com",
    helperLabel: "前往 console.anthropic.com 获取密钥",
    warning: "建议使用 claude-sonnet-4-5 及以上版本（需 200K 上下文）",
    models: [
      {
        id: "claude-opus-4-5",
        label: "claude-opus-4-5",
        context: "128K ctx",
        tags: ["Smartest", "Slower"],
      },
      {
        id: "claude-sonnet-4-5",
        label: "claude-sonnet-4-5",
        context: "200K ctx",
        tags: ["Balanced", "⭐ Best value"],
        recommended: true,
      },
      {
        id: "claude-haiku-4-5",
        label: "claude-haiku-4-5",
        context: "200K ctx",
        tags: ["Fast", "Cheapest"],
      },
    ],
  },
  {
    id: "openai",
    name: "OpenAI",
    short: "OpenAI",
    symbol: "◉",
    description: "GPT-4o / o3 系列",
    keyLabel: "OpenAI API Key",
    keyPlaceholder: "sk-••••••••",
    helperUrl: "https://platform.openai.com",
    helperLabel: "前往 platform.openai.com 获取密钥",
    models: [
      { id: "gpt-4o", label: "gpt-4o", context: "128K ctx", tags: ["Smartest", "Slower"] },
      {
        id: "gpt-4o-mini",
        label: "gpt-4o-mini",
        context: "128K ctx",
        tags: ["Fast", "Cheap"],
        recommended: true,
      },
      { id: "o3-mini", label: "o3-mini", context: "200K ctx", tags: ["Reasoning", "API beta"] },
      { id: "gpt-4.1", label: "gpt-4.1", context: "1M ctx", tags: ["Latest"] },
    ],
  },
  {
    id: "google",
    name: "Google Gemini",
    short: "Gemini",
    symbol: "✦",
    description: "Gemini 2.5 系列 · 1M 上下文",
    keyLabel: "Google AI API Key",
    keyPlaceholder: "AIza••••••••",
    helperUrl: "https://aistudio.google.com",
    helperLabel: "前往 aistudio.google.com 获取密钥",
    models: [
      {
        id: "gemini-2.5-pro",
        label: "gemini-2.5-pro",
        context: "1M ctx",
        tags: ["Smartest"],
        recommended: true,
      },
      { id: "gemini-2.5-flash", label: "gemini-2.5-flash", context: "1M ctx", tags: ["Fast"] },
    ],
  },
  {
    id: "deepseek",
    name: "DeepSeek",
    short: "DeepSeek",
    symbol: "▲",
    description: "DeepSeek-Chat / Reasoner",
    keyLabel: "DeepSeek API Key",
    keyPlaceholder: "sk-••••••••",
    helperUrl: "https://platform.deepseek.com",
    helperLabel: "前往 platform.deepseek.com 获取密钥",
    models: [
      {
        id: "deepseek-chat",
        label: "deepseek-chat",
        context: "64K ctx",
        tags: ["Balanced"],
        recommended: true,
      },
      {
        id: "deepseek-reasoner",
        label: "deepseek-reasoner",
        context: "64K ctx",
        tags: ["Reasoning mode"],
      },
    ],
  },
  {
    id: "groq",
    name: "Groq",
    short: "Groq",
    symbol: "○",
    description: "极速推理（fast inference）",
    keyLabel: "Groq API Key",
    keyPlaceholder: "gsk_••••••••",
    helperUrl: "https://console.groq.com",
    helperLabel: "前往 console.groq.com 获取密钥",
    models: [
      {
        id: "llama-3.3-70b-versatile",
        label: "llama-3.3-70b-versatile",
        context: "128K ctx",
        tags: ["Best quality on Groq"],
        recommended: true,
      },
      { id: "mixtral-8x7b-32768", label: "mixtral-8x7b-32768", context: "32K ctx", tags: ["Fast"] },
    ],
  },
  {
    id: "azure",
    name: "Azure OpenAI",
    short: "Azure",
    symbol: "⊞",
    description: "Azure 托管的 OpenAI 部署",
    keyLabel: "Azure API Key",
    keyPlaceholder: "•••••",
    models: [
      {
        id: "azure-deployment",
        label: "Your deployment",
        context: "—",
        tags: ["Custom"],
        recommended: true,
      },
    ],
  },
  {
    id: "custom",
    name: "Custom / OpenAI-compatible",
    short: "Custom",
    symbol: "···",
    description: "自定义 OpenAI 兼容端点",
    keyLabel: "API Key",
    keyPlaceholder: "•••••",
    models: [
      {
        id: "custom-model",
        label: "Your model",
        context: "—",
        tags: ["Custom"],
        recommended: true,
      },
    ],
  },
]

export function getProvider(id: string | null | undefined) {
  return PROVIDERS.find((p) => p.id === id) ?? null
}
